[package]
authors = ["Nikhil Prabhu <nikhilprabhu00@gmail.com>"]
edition = "2018"
name = "dotman"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
chrono = "0.4"
git2 = "0.13.20"
structopt = "0.3.21"
